### ISSUE TITLE
contentful.contentType(id) bypassing arguments

### ISSUE THREAD

**Issue by lucas-bittar-ir** [jvandemo/angular-contentful#10]
Hey!

I was trying to use the contentful.contentType(id) passing the contentType id via controller but it ends up fetching the whole API instead of the specific one. To solve that problem I had to use the directives method although I really want to have that in the backstage instead of in the HTML.

Here´s the example:

``` javascript
angular
     .module('app')
     .controller('HomeEvents', function ($scope, contentful) {

       var contentType = '43ynb0LYp2eckqQss68os4';

       // Get all entries
       contentful
         .entries({ content_type: contentType })
         .then(

           // Success handler
           function(response){
             var entries = response.data;

             $scope.events = entries.items;

           },

           // Error handler
           function(response){
             console.log('Oops, error ' + response.status);
           }
       );

     }); 
```

Could you take a look at that please?

GREAT lib! Thank you so much!

**Comment by jvandemo** [comment]
Hi @lucas-bittar-ir, the `contentful.entries()` method only accepts a string as argument (not an object).

So `contentful.entries('content_type=' + contentType)` should give you the desired outcome.

Can you try and see if it works? Thanks!!

**Comment by lucas-bittar-ir** [comment]
Hey @jvandemo!

Worked perfectly! Thank you so much for the assistance and for replying so quickly! I really appreciate.

Take care!

**Comment by jvandemo** [comment]
Hi @lucas-bittar-ir, glad to hear it works!

Thanks for your kind feedback!
