### ISSUE TITLE
pull in content from more than one space

### ISSUE THREAD

**Issue by wanderingcrow** [jvandemo/angular-contentful#13]
Hello, this isn't an issue with the repo, more like an issue with me, but how would I pull in content from more than one contentful space? 

Great repo, btw; it was quite easy to get this up and working.

**Comment by jvandemo** [comment]
@javaporter &mdash; Currently it is not supported to connect to multiple spaces.

I will think about a way to support this without breaking the current API.

Can you describe your use-case a little more in-depth so I can get a feel of your exact needs?

Thanks in advance!

**Comment by wanderingcrow** [comment]
@jvandemo The client has several editors from various countries. We set up one space for the American team to edit the majority of the site, but the int'l teams need to edit their specific pages. From what I can tell, Contentful does not have a way to assign users permissions the ability to edit some content types, but not others, so I made a new space just for the int'l teams. Does that help?

**Comment by jvandemo** [comment]
@javaporter &mdash; I've investigated your issue and it would require an overall rewrite of the current code and possibly introduce breaking changes for current users.

I think Contentful is working on roles that may allow you to accomplish this from one space.

Maybe it is worth talking to them first to see if they can come up with a solution for your team (they have a great support team)?

Thanks!

**Comment by wanderingcrow** [comment]
@jvandemo I think you're right. I have spoken to them a little and it seems this might be on the horizon. I'll close the issue.

**Comment by jvandemo** [comment]
@javaporter &mdash; That is great news, thanks for your feedback!
