### ISSUE TITLE
Incorrect 'orderBy' syntax

### ISSUE THREAD

**Issue by sollenne** [jvandemo/angular-contentful#14]
The docs show you should use `| orderBy:'dog.fields.name` as show in your example:

```
<ul contentful-entries="'content_type=dog'">
  <li ng-repeat="dog in $contentfulEntries.items | orderBy:'dog.fields.name' ">
    <h1>{{ dog.fields.name }}</h2>
    <img ng-src="{{ dog.fields.image.fields.file.url }}" />
  </li>
</ul>
```

However; This didn't work for me and cascading through the objects, I found that I needed to drop the category name in the `orderBy` filter and only apply it as `| orderBy:'fields.name'` as shown below:

```
<ul contentful-entries="'content_type=dog'">
  <li ng-repeat="dog in $contentfulEntries.items | orderBy:'fields.name' ">
    <h1>{{ dog.fields.name }}</h2>
    <img ng-src="{{ dog.fields.image.fields.file.url }}" />
  </li>
</ul>
```

Just a heads up that you may want to update the docs, or if they are correct and I'm using them incorrectly I'd appreciate the feedback.

**Comment by jvandemo** [comment]
@sollenne &mdash; You are absolutely right, good catch. I have updated the documentation.

Thank you for your input, much appreciated! 👍
