### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by KasperAndersson** [jvandemo/angular-contentful#15]

**Comment by jvandemo** [comment]
@KasperAndersson &mdash; I have added the library to npm:
https://www.npmjs.com/package/angular-contentful

I have also added the installation instructions to the README:

https://www.npmjs.com/package/angular-contentful

``` bash
$ npm install angular-contentful
```

Can you let me know if everything works as expected?

Thanks for your input!

**Comment by KasperAndersson** [comment]
@jvandemo Thanks, it works!
