### ISSUE TITLE
Contentful Preview API

### ISSUE THREAD

**Issue by neilkyoung** [jvandemo/angular-contentful#16]
Is there anyway to flip to Contentful's preview API using this module?

**Comment by jvandemo** [comment]
Yes, you can set the `host` option in a `config` block using the `contentfulProvider` provider:

``` javascript
angular
  .module('yourApp')
  .config(function(contentfulProvider){
    contentfulProvider.setOptions({
        host: 'preview.contentful.com',
        space: 'yourSpace',
        accessToken: 'yourAccessToken'
    });
  });
```

By default the `host` option is set to `cdn.contentful.com` but you can set it to `preview.contentful.com` to use Contentful's preview API.

Can you let me know if it works as expected so I can close this issue?

Thanks!

**Comment by neilkyoung** [comment]
Ah I see. That works perfectly. Thank you for your quick response.

**Comment by jvandemo** [comment]
@neilkyoung &mdash; My pleasure, thank you for your feedback!
