### ISSUE TITLE
Using angular-contentful in Angular 2.0

### ISSUE THREAD

**Issue by lukewduncan** [jvandemo/angular-contentful#25]
Hi,

Just wondering if you've seen any success of people using this module in an angular 2.0 application. I am starting a new Ionic project and i've used this before in previous Angular 1.0 applications and loved it. 

Just wondering how you would go about using this in an Angular 2.0 project if it is possible.

**Comment by jvandemo** [comment]
@lukewduncan &mdash; I'm sorry; I'm afraid this library is written for AngularJS and will not work in Angular. I'm not aware of any Angular alternatives yet either.
