### ISSUE TITLE
Example for searching array field with in operator

### ISSUE THREAD

**Issue by lijulat** [jvandemo/angular-contentful#27]
Hi,

Could you give me an example for searching contentful entries using contentful service . I would like to search a field of type array using all, In, Ne operators .

Thanks

**Comment by jvandemo** [comment]
@lijulat You can specify a query string when calling `contentful.entries`:

```javascript
contentful.entries(queryString);
```

For example:

```javascript
contentful.entries('content_type=dog&limit=10');
```

You can find more about the supported search parameters on the Contentful website: https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters.

Hope that helps! 👍
