### ISSUE TITLE
How can I sort the contentful response on the frontend?

### ISSUE THREAD

**Issue by ohabash** [jvandemo/angular-contentful#28]
I love contentful but it would be half as great without your work. Thanks!

How can I sort the contentful response on the frontend? Below is my attempt.

https://jsfiddle.net/k3jmq2gm/1/

```
<div class="columns teams-list" contentful-entries="'content_type=staff'" ng-controller="teamContentful">
	<div ng-repeat="item in $contentfulEntries.items | orderBy:'item.fields.name'" class="column" data-flag="{{item.fields.flag}}" data-visible="{{item.fields.visible}}" ng-class='{active:$first}' data-tab="1" data-title="{{item.fields.title}}" data-name="{{item.fields.name}}">
		<!-- <h1>{{item[0].title}}</h1> -->
		<img src="{{ item.fields.image.fields.file.url }}" title="{{item.img}}">
		<p class="hide bio">{{item.fields.bio}}</p>
	</div>
</div>
```

**Comment by jvandemo** [comment]
@ohabash &mdash; Thank you for your kind words, much appreciated.

Your attempt is almost correct. You should use `orderBy:'fields.name'` instead of `orderBy:'item.fields.name'`.

Can you see if that works for you? Thanks!

**Comment by ohabash** [comment]
It does work... It was bitter sweet that the answer was so simple. Thank you!

**Comment by jvandemo** [comment]
@ohabash &mdash; Awesome, great to hear. Thank you for the update! 👍
