### ISSUE TITLE
Multiple spaces: requests are missing the host 

### ISSUE THREAD

**Issue by wrmz** [jvandemo/angular-contentful#29]
I may be doing something incorrectly here, so I apologize for my ignorance if that's the case.

I have a **contentful.config.js** file that has the following so that I can reference multiple spaces:

```js
function ContentfulConfig(contentfulProvider) {
    contentfulProvider.setOptions({
        'default': {
            space: `${space_id}`,
            accessToken: `${access_token}`
        },
        'another': {
            space: `${space_id}`,
            accessToken: `${access_token}`
        }
    });
}
ContentfulConfig.$inject = ['contentfulProvider'];
export default ContentfulConfig;
```

In my **app.routes.js** I have the following (using ui-router):

```js
function appRoutes($stateProvider) {
    $stateProvider
        ...
        .state('app.cli', {
            url: '/cli',
            template: cliTemplate,
            controller: 'CLIController as cli',
            resolve: {
                contents: ['contentful', (contentful) => {
                    return contentful
                        .entries('', 'jscli')
                        .then((response) => {
                            return response.data;
                        }, (error) => {
                            console.log(`Error: ${response.status}`);
                        });
                }]
            }
        });
}
appRoutes.$inject = ['$stateProvider'];
export default appRoutes;
```
When navigating to this page, so that a call is made to the API for the requested data, I was getting a malformed URI error. 

Delving in I found that the request was going to `http://:80/spaces/${space_id}/entries`.

It was missing the host. 

Ensuring that the host is supplied among the options in **contentful.config.js** for each space resolved the issue. 

I'm assuming that this might be as easy as adding this instruction to the documentation examples, but I didn't dig deep enough to learn why the host wasn't remaining intact when merged on line 313 of **angular-contentful.js** in `this.setOptions()` method.

Edit: grammar.

**Comment by jvandemo** [comment]
@wrmz &mdash; we have updated the documentation to be more explicit:

```javascript
angular
  .module('yourApp')
  .config(function(contentfulProvider){
    contentfulProvider.setOptions({
        'default': {
          host: 'cdn.contentful.com',
          space: 'first_space',
          accessToken: 'first_token'
        },
        'another': {
          host: 'cdn.contentful.com',
          space: 'second_space',
          accessToken: 'second_token'
        }
        ...
    });
  });
```

Thank you for your feedback, much appreciated! 👍
