### ISSUE TITLE
Strict Contextual Escaping

### ISSUE THREAD

**Issue by imjustabillr** [jvandemo/angular-contentful#3]
This isn't an issue, but rather a question. Is there a way to disable sce for certain fields? I need to display my fields with the html markup provided by a contentful text field.

**Comment by jvandemo** [comment]
@imjustabillr &mdash; Yes, you can use `angular-sanitize` to do that.

Personally I use the [angular markdown directive](https://github.com/btford/angular-markdown-directive)  to display markdown content like this:

``` html
<div btf-markdown="entry.fields.markdown"></div>
```

The `btf-markdown` directive uses the `angular-sanitize` module internally and takes care of displaying everything correctly for you.

Does that answer your question? Thanks!

**Comment by imjustabillr** [comment]
Yes. That does help, but I'm having issues getting either method integrated. I know that the angular markdown directive that you pointed me to is half working in my code. It will successfully mark up an external file :
    `<div btf-markdown ng-include="'README.md'"></div>`

but fails if I either use the markup in the html itself
    `<btf-markdown>
        #Markdown directive
        *It works!*
    </btf-markdown>`

or if I try a contenful tag
    `<div btf-markdown>{{ $contentfulEntry.fields.textTechnology }}</div>`

I've even tried
    `<div btf-markdown="entry.fields.textTechnology"></div>`

In my code, I've included angular.min.js, angular-sanitize.js, angular-contentful.min.js, showdown.js and markdown.js. I've added btford.markdown and contentful as module dependencies, and I've configured contentful to use my space and access token. I can display a contentful Entry, it just isn't being marked up by any of the methods I've mentioned above.

There's got to be something stupid and simple that I'm missing. Can you please point me in the right direction?

**Comment by jvandemo** [comment]
@imjustabillr &mdash; Can you try:

``` html
<div btf-markdown="$contentfulEntry.fields.textTechnology"></div>
```

If you can see the contentful entry and the `btf-markdown` directive is working, it should work.

Thanks!

**Comment by imjustabillr** [comment]
That did it! Thank you very much! I didn't realize that the syntax for calling the entry needed to change as well. Thank you for your help!

**Comment by jvandemo** [comment]
@imjustabillr &mdash; Awesome, great to hear! Thanks for the feedback!

**Comment by vergarm** [comment]
Hi! I'm having the same issue when using the directive markdown and also followed the above comments by removing the  {{ curly braces around the contentful field but no luck.
`<div` `btf-markdown="$contentfulEntry.fields.footerText"></div>`
I have all the same stuff referenced in my library: angular.min.js, angular-sanitize.js, angular-contentful.min.js, showdown.js and markdown.js.  I also have the  btford.markdown module dependencies initialized. I can see the contentful entry but it doesnt translate the markdown and renders thing as is. Please advise. Thanks

**Comment by jvandemo** [comment]
@vergarm &mdash; What exactly are you seeing? Are you seeing any output at all?

Feel free to paste a link here to the code or plunk if you it is publicly available.

Thanks!

**Comment by vergarm** [comment]
@jvandemo - the contentful entry contains a copyright symbol and when it renders it doesnt convert the copyright and renders it as `&copy;`

**Comment by vergarm** [comment]
@jvandemo - i'm seeing the output but it doesnt translate the markdown of the contentful entry. Unfortunately this site is company site so i cannot share the link but the contentful entry value looks like this: `<sup>&reg;</sup> is a registered trademark of`

**Comment by vergarm** [comment]
@jvandemo - I made a public site, here is the link if you want to check it out.
http://dev.contentful.tevausa.com/

The markdown is on the footer of the page. You will see the `&reg;` and `&copy;` symbols not getting marked up. Thanks

**Comment by jvandemo** [comment]
@vergarm &mdash; Here is a working plunk with the `&copy;` entity using `btf-markdown`:
http://plnkr.co/edit/Pd6rJ4qcJaJbb1152vO6?p=preview

Are you using similar code to display your HTML?

**Comment by vergarm** [comment]
@jvandemo - thanks for providing the plunk. I have a contentful entry and doing it btf-markdown directive style:
`<div btf-markdown="$contentfulEntry.fields.footerText"></div>` 

The problem is it wont mark up.

**Comment by vergarm** [comment]
Hi @jvandemo - do you have an example of using this as a directive with a contentful entry instead of using a controller and $scope variable?

I dont have a controller nor scope variabled because my entry is coming from a contentful API.
`<div btf-markdown="$contentfulEntry.fields.footerText"></div>`

**Comment by jvandemo** [comment]
@vergarm &mdash; Does it work correctly if you pass in the same content via a scope variable (instead of using `$contentfulEntry`)? Thanks!

**Comment by vergarm** [comment]
@jvandemo - Yes, it does work when the same content us via scope variable. Unfortunately, it needs to come from $contentfulEntry and this is where I'm stuck right now.

**Comment by jvandemo** [comment]
@vergarm &mdash; Can you provide with me with a screenshot of how the data is entered in Contentful (of the editor page) so I can try and replicate it here? Or is the space (and entry) publicly accessible? If so, feel free to provide me with the space ID and entry ID. Thanks again!

**Comment by vergarm** [comment]
@jvandemo - here you go. I've attached a screenshot of the contentful entry in editor mode. The fieldname is footerText.  Thanks for your help!
![contentful](https://cloud.githubusercontent.com/assets/8237567/17283001/d15748a8-5779-11e6-973f-06eccefaf334.PNG)

**Comment by vergarm** [comment]
@jvandemo - i figured it out. :-)

i needed to add  ng-bind-html like below:
`<p id="regtrademark"  ng-bind-html="$contentfulEntry.fields.footerText"></p>`

and also added ngSanitize as a dependency.
`app.module('app',` ['ngSanitize']);`

Now, the markdown is working and the $contentfulentry is visible. :-) Thanks again for your help.

**Comment by jvandemo** [comment]
@vergarm &mdash; Thanks for the update, glad to hear you figured it out! 👍
