### ISSUE TITLE
filter don't work

### ISSUE THREAD

**Issue by ghost** [jvandemo/angular-contentful#5]
Hi!
I can't apply filters as object like contentful.entry({"content_type":"foo"}).then()...
is that a problem with your library or with contentful?

**Comment by jvandemo** [comment]
Hi @happschinson,
- `contentful.entry(id)` only accepts an `id` string as argument
- `contentful.entries(queryString)` only accepts a `queryString` string as argument (the same string you would use when connecting directly to the Contentful API

so you can:

```
// fetch a single entry using its ID
contentful.entry('6KntaYXaHSyIw8M6eo26OK');

// fetch multiple entries using filters
contentful.entries('content_type=foo');
```

Can you give that a try? Thanks!

**Comment by jvandemo** [comment]
Closed due to lack of response.
