### ISSUE TITLE
Brackets gets converted to entities

### ISSUE THREAD

**Issue by fredrik-sogaard** [jvandemo/angular-contentful#8]
When I try to use a variable with double curly brackets they get converted to entities in the resulting get request.

```
<div contentful-entry="{{ eventId }}">{{ $contentfulEntry | json }}</div>
```

becomes

```
https://cdn.contentful.com/spaces/osmot86btiv3/entries/%7B%7BeventId%7D%7D
```

Is there a way to solve this?

**Comment by jvandemo** [comment]
Hi @fredrik-sogaard &mdash; Currently only literal strings are supported, not expressions.

You can use the `contentful.entry(id)` method to fetch a single entry if you need to do so programmatically.

Please let me know if you feel expressions are needed in the directive.

I am considering adding expression support but since that is a breaking feature, I will have to release a v2.0.0 for that.

Thanks for your feedback!

**Comment by jvandemo** [comment]
Hi @fredrik-sogaard &mdash; I have just released v2.0.0 with support for expressions in the development branch: https://github.com/jvandemo/angular-contentful/tree/development

In v2.0.0 you can use expressions by default:

``` xml
<div contentful-entry="eventId">{{ $contentfulEntry | json }}</div>
```

and use literals if you want to specify a string:

``` xml
<div contentful-entry="'some-literal-id'">{{ $contentfulEntry | json }}</div>
```

Can you try it out and let me know if it works for you?

Thanks!

**Comment by fredrik-sogaard** [comment]
Thanks! That was fast!

One thing I found: I can't access the file url of a linked asset from an entry? I only have access to the "sys" fields.

**Comment by jvandemo** [comment]
Hi @fredrik-sogaard,

That is the default behavior of Contentful (see https://www.contentful.com/developers/documentation/content-delivery-api/#search-link).

You can specify the levels of resolved content like this:

``` xml
<pre contentful-entry="'sys.id=6KntaYXaHSyIw8M6eo26OK&include=3'">
  {{ $contentfulEntry | json }}
</pre>
```

Can you try and verify if this works for you? Thanks!

**Comment by fredrik-sogaard** [comment]
Thanks a lot for your replies. Really appreciate it!

Angular-contenful normally auto resolves links, so I thought perhaps it would also do it in this case. Because if I just get all the contentful entries, I can get the image url directly.

**Comment by jvandemo** [comment]
@fredrik-sogaard &mdash; Correct, when querying for multiple entries, this happens automatically. That is how the Contentful API works.

I have added documentation to the README to hopefully avoid confusion for others if they are in a similar situation.

Thanks for your feedback. I will close this issue but if you feel you have additional feedback, please don't hesitate to add it here. Thanks!

**Comment by fredrik-sogaard** [comment]
Hi @jvandemo,

I have one small problem with this. Let me try to explain:

I set the eventID in the controller like this: `$scope.eventId = $stateParams.eventId + '&include=1';`

Which in turn I can log out and get `4DSqMNTzeMKGSgi6ckGQ60&include=1` as I would expect and everything seems to work.

But if I look in my network tab in web inspector I see this request: `https://cdn.contentful.com/spaces/osmot86btiv3/entries?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxx&include=1` (access token redacted here)

This results in that every item in my list of events gets the same data.

If I remove `&include=1` from the controller I get this (correct) request: `
https://cdn.contentful.com/spaces/osmot86btiv3/entries/4DSqMNTzeMKGSgi6ckGQ60?access_token=xxxxxxxxxxxxxxxxxxxxxxxx`

Any idea of what's going on here?

**Comment by jvandemo** [comment]
What does your template look like @fredrik-sogaard? Thanks!
